### ISSUE TITLE
docs: cli examples don't execute expectedly

### ISSUE THREAD

**Issue by loganrussell48** [VeryGoodOpenSource/very_good_flutter_plugin#123]
### Problem
The examples in the readme don't properly execute to achieve what the docs say. 
### Expected behavior
`very_good create my_plugin -t flutter_plugin` should create a plugin named "my_plugin" with all defaults

### What actually happens
`Could not find an option or flag "-t".`  (presumably, the `-t` flag has been replaced with some other syntax)
## **Requirements**

- [ ] All code examples in README.md should execute properly

**Comment by renancaraujo** [comment]
The readme is outdated :/

For the current usage of the very good CLI, see the docs at https://cli.vgv.dev/

Using this card to track the readme update
