### ISSUE TITLE
A lot of (Android) deficiencies are outdated

### ISSUE THREAD

**Issue by rekire** [VeryGoodOpenSource/very_good_flutter_plugin#146]
**Description**

As discussed in #144 I had some trouble to make it running, but now I was able to generate the code and to diff it with my existing code. While there are huge improvements for my code base regarding CI I noticed that a lot of dependencies are very outdated.

**Outdated versions**

- The Gradle wrapper you ship 6.7; I'm currently using 8.1, but there is already 8.5 (however I'm not sure if that version is already compatible)
- In a all `AndroidManifest.xml` is still a `package` attribute, that is outdated and should not used anymore AFIK
- Your `build.gradle` references kotlin 1.6.10 (in another file even 1.3.50 was referenced) the latest version is 1.9.22
- Your `build.gradle` references the android gradle plugin 4.1.0 the latest version is 8.3

**Comment by alestiago** [comment]
Hi @rekire 👋  ! Thanks for opening this issue.

We need to check this dependencies, if indeed they have to be updated, would you like contributing with a Pull Request?

**Comment by tomarra** [comment]
> General I would like, but I do not really understand yet, which files I would need to edit and which would needs to be regenerated. If you have some documentation I would check what I can do.

Fair point. We don't have a CONTRIBUTING.md in this repo yet. Here are some points to get you started.

- Complete the needed updates in the `src/my_plugin` folder. This allows you to run things locally and ensure that the changes are working correctly.
- Open a PR with the changes in the `src/my_plugin` folder so it can be checked against the CI pipeline and go through the normal review process. 
- When the changes are accepted and merged into `main` the `generate_template.yaml` workflow will kick off to make the needed changes to the brick.

Hope this helps and looking forward to seeing the contribution :)
