### ISSUE TITLE
feat: swift support for iOS and macOS plugin 

### ISSUE THREAD

**Issue by orestesgaolin** [VeryGoodOpenSource/very_good_flutter_plugin#43]
**Description**

I'd like to request for Swift support being enabled out of the box for iOS and macOS plugin.

**Expected Behavior**
I tend to convert the plugin to use Swift every time I use it and I figured it would be convenient to have it like that from the start.

**Screenshots**

Default files are Obj-C

<img width="716" alt="CleanShot 2022-08-21 at 01 10 37@2x" src="https://user-images.githubusercontent.com/16854239/185768990-89b149ee-dfcb-490c-a789-53f9786976d0.png">

**Comment by renancaraujo** [comment]
related: https://github.com/VeryGoodOpenSource/very_good_cli/issues/370

**Comment by tomarra** [comment]
Looks likes this was completed via https://github.com/VeryGoodOpenSource/very_good_cli/issues/370 Closing this out
