### ISSUE TITLE
tests: add native unit tests and lint integration

### ISSUE THREAD

**Issue by felangel** [VeryGoodOpenSource/very_good_flutter_plugin#62]
As a developer, I'd like to have native unit tests for the platform-specific code in addition to the integration tests so that I have a reference for how to write native tests when building out a real-world plugin. Also, native lint integration.

**Comment by BeatriceMitchell** [comment]
Let's tackle this after completing https://github.com/VeryGoodOpenSource/very_good_cli/issues/370

**Comment by tomarra** [comment]
One year and no upvotes or action on this, closing as "Won't Fix"

**Comment by alestiago** [comment]
I think we should fix this at some point, it aligns with our values "Do the best professional work" 🙌
