### ISSUE TITLE
fix: flaky integrated tests

### ISSUE THREAD

**Issue by renancaraujo** [VeryGoodOpenSource/very_good_flutter_plugin#79]
**Description**
Integration tests have been flaky since [the update to flutter 3.7.0](https://github.com/VeryGoodOpenSource/very_good_flutter_plugin/pull/77).

Specifically, android, macos and linux. 

https://github.com/flutter/flutter/issues/50898
Android: Fails almost all the time. Possibly related: https://github.com/flutter/flutter/issues/50898
macOS: Fails every time.
Linux: Faield once in 10 workflow runs.

**Comment by bartekpacia** [comment]
![1yvlfp](https://user-images.githubusercontent.com/40357511/217568484-a3ec5147-48c4-4bdb-b933-c78a65f39133.jpg)

**Comment by wolfenrain** [comment]
In the Flutter 3.7 release they [dropped support for OpenGL on macOS platform](https://github.com/flutter/flutter/issues/119994). And Github macOS runner [does not support metal currently](https://github.com/actions/runner-images/discussions/6138) so the macOS e2e tests are dead in the water for now.

**Comment by renancaraujo** [comment]
ref:  #79

**Comment by renancaraujo** [comment]
Closed on https://github.com/VeryGoodOpenSource/very_good_flutter_plugin/pull/125
