### ISSUE TITLE
refactor: generator code to be simplified

### ISSUE THREAD

**Issue by alestiago** [VeryGoodOpenSource/very_good_flutter_plugin#96]
**Description**

As discussed, the generator script is complicated and very "hacky". The tool should be refactored to be more comprehensive and facilitate its maintenance. In addition, testing the generator would be helpful to prevent issues like #87 .

**Requirements**

- [ ] Fully testes generator code
- [ ] Simplified and well documented generation process

**Comment by alestiago** [comment]
We need to ensure https://github.com/VeryGoodOpenSource/very_good_flutter_plugin/issues/152 is resolved.

**Comment by tomarra** [comment]
We have this unblocked now so moving to ToDo.
